export const DEGREE_OPTIONS = [
  "Apprenticeship",
  "Associates",
  "Bachelors",
  "Diploma",
  "Doctorate",
  "High School Diploma",
  "Master of Crafts",
  "Masters",
  "Other",
  "Trade School",
];

export const FIELD_OF_STUDY_OPTIONS = [
  "Accounting",
  "Anthropology",
  "Architecture",
  "Arts",
  "Biochemistry",
  "Biological Science",
  "Biology",
  "Business",
  "Chemical Engineering",
  "Chemistry",
  "Civil Engineering",
  "Communication",
  "Comparative Literature",
  "Computer Science",
  "Criminal Justice",
  "Design",
  "Drafting",
  "Economics",
  "Education",
  "Electrical Engineering",
  "Electronics",
  "Engineering General",
  "Engineering Management",
  "English",
  "Environmental Engineering",
  "Environmental Science",
  "Film",
  "Finance",
  "Fine Arts",
  "Forestry",
  "General Studies",
  "Geography",
  "Geology",
  "Government",
  "Healthcare",
  "History",
  "Hospitality Management",
  "Human Resource Management",
  "Human Resources",
  "Information Systems",
  "Law",
  "Liberal Arts",
  "Linguistics",
  "Literature",
  "Marketing",
  "Mathematics",
  "Mechanical Engineering",
  "Media",
  "Music",
  "Nursing",
  "Organizational Development",
  "Other",
  "Other Technology",
  "Pharmacy",
  "Philosophy",
  "Physics",
  "Political Science",
  "Project Management",
  "Public Relations",
  "Religion",
  "Science",
  "Sociology",
  "Statistics",
  "Theatre",
  "Visual Arts",
];
